// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.IO;


namespace UBS
{
	public class BuildConfiguration
	{
		public BuildConfiguration ()
		{
			DirectoryInfo di = new DirectoryInfo( Application.dataPath );

			AssetsDirectory = di.FullName;
			ResourcesDirectory = Path.Combine( AssetsDirectory , "Resources");
			ProjectDirectory = di.Parent.FullName;
		}

		public string ResourcesDirectory
		{
			get;
			private set;
		}

		public string AssetsDirectory
		{
			get;
			private set;
		}

		public string ProjectDirectory
		{
			get;
			private set;
		}

	}
}

