// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.IO;


namespace UBS
{
	[Serializable]
	public class BuildConfiguration
	{
		public BuildConfiguration ()
		{
			DirectoryInfo di = new DirectoryInfo( Application.dataPath );

			AssetsDirectory = di.FullName;
			ResourcesDirectory = Path.Combine( AssetsDirectory , "Resources");
			ProjectDirectory = di.Parent.FullName;
		}

		[SerializeField]
		string mResourcesDirectory;

		
		[SerializeField]
		string mAssetsDirectory;

		[SerializeField]
		string mProjectDirectory;

		public string ResourcesDirectory
		{
			get { return mResourcesDirectory; }
			private set { mResourcesDirectory = value; }
		}

		public string AssetsDirectory
		{
			get { return mAssetsDirectory; }
			private set { mAssetsDirectory = value; }
		}

		public string ProjectDirectory
		{
			get { return mProjectDirectory; }
			private set { mProjectDirectory = value; }
		}

	}
}

