// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace UBS
{
	public interface IBuildStepProvider
	{

		/// <summary>
		/// Called by the Buildsystem if your build step Provider is requested to start its build step
		/// </summary>
		/// <param name="pConfiguration">configuration.</param>
		void BuildStepStart(BuildConfiguration pConfiguration);
		/// <summary>
		/// Called as an update method every "frame" to allow continuous processing of async operations
		/// </summary>
		void BuildStepUpdate();
		/// <summary>
		/// Determines whether this instance is done.
		/// </summary>
		/// <returns><c>true</c> if this instance is done; otherwise, <c>false</c>.</returns>
		bool IsBuildStepDone();
		

	}
}

